spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: config-client-dev
server:
  port: 7100

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.com:8001/eureka


---
spring:
  profiles: test
  appliction:
    name: config-client-test
server:
  port: 7200

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2.com:8002/eureka