username: 洪荒之力PDD
info:
  app-name: ${spring.application.name}
  instance_id: ${spring.application.instance_id}
  hostname: ${spring.cloud.client.hostname}
  customer: ${eureka.instance.instance-id}
  username: ${username}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:@localhost:3306/springboot?useSSL=false
    username: root
    password: root