spring:
  profiles:
    active:
    - pro
---

spring:
  profiles: dev
  application:
    name: eureka-zuul-dev

zuul:
  routes:
    service1.serviceId: eureka-client1
    service1.path: /client1/** #代理服务名
    service2.serviceId: client-feign
    service2.path: /feign/**
---
spring:
  profiles: pro
  application:
    name: eureka-zuul-pro
zuul:
  routes:
    app-a.serviceId: eureka-client1
    app-a.path: /app-a/**
    app-b.serviceId: client-feign
    app-b.path: /app-b/**
